### ISSUE TITLE
unexpected result from example code

### ISSUE THREAD

**Issue by heistp** [mikioh/tcpinfo#2]
I tried running the tcpinfo code from doc.go (just putting the exact code into a main.go) and expected to JSON output with keys and values perhaps, but I get this:

`[123 34 97 116 111 34 58 48 44 34 99 111 110 103 95 99 116 108 34 58 123 34 115 110 100 95 115 115 116 104 114 101 115 104 34 58 49 48 55 51 55 50 53 52 52 48 44 34 114 99 118 95 115 115 116 104 114 101 115 104 34 58 48 44 34 115 110 100 95 99 119 110 100 95 98 121 116 101 115 34 58 52 51 56 48 44 34 115 110 100 95 99 119 110 100 95 115 101 103 115 34 58 48 125 44 34 102 108 111 119 95 99 116 108 34 58 123 34 114 99 118 95 119 110 100 34 58 49 51 49 51 50 56 125 44 34 108 97 115 116 95 97 99 107 95 114 99 118 100 34 58 48 44 34 108 97 115 116 95 100 97 116 97 95 114 99 118 100 34 58 48 44 34 108 97 115 116 95 100 97 116 97 95 115 101 110 116 34 58 48 44 34 111 112 116 115 34 58 123 34 115 97 99 107 34 58 116 114 117 101 44 34 116 109 115 116 97 109 112 115 34 58 116 114 117 101 44 34 119 115 99 97 108 101 34 58 56 125 44 34 112 101 101 114 95 111 112 116 115 34 58 123 34 115 97 99 107 34 58 116 114 117 101 44 34 116 109 115 116 97 109 112 115 34 58 116 114 117 101 44 34 119 115 99 97 108 101 34 58 53 125 44 34 114 99 118 95 109 115 115 34 58 49 51 54 56 44 34 114 116 111 34 58 48 44 34 114 116 116 34 58 49 51 48 48 48 48 48 48 44 34 114 116 116 118 97 114 34 58 54 48 48 48 48 48 48 44 34 115 110 100 95 109 115 115 34 58 49 51 54 56 44 34 115 116 97 116 101 34 58 34 101 115 116 97 98 108 105 115 104 101 100 34 44 34 115 121 115 34 58 123 34 102 108 97 103 115 34 58 48 44 34 115 110 100 95 119 110 100 34 58 52 50 52 48 56 44 34 115 110 100 95 105 110 117 115 101 34 58 48 44 34 115 114 116 116 34 58 49 51 48 48 48 48 48 48 44 34 115 101 103 115 95 115 101 110 116 34 58 48 44 34 98 121 116 101 115 95 115 101 110 116 34 58 48 44 34 114 101 116 114 97 110 115 95 98 121 116 101 115 34 58 48 44 34 115 101 103 115 95 114 99 118 100 34 58 48 44 34 98 121 116 101 115 95 114 99 118 100 34 58 48 44 34 111 111 111 95 98 121 116 101 115 95 114 99 118 100 34 58 48 44 34 114 101 116 114 97 110 115 95 115 101 103 115 34 58 48 125 125]
`

This happens with both Go 1.9.2 on darwin/amd64 and Go 1.8.3 on linux/arm.

**Comment by mikioh** [comment]
Please take a look at the documentation on Marshal function of encoding/json package. It returns a slice of byte, not string, s/fmt.Println(txt)/fmt.Println(string(txt))/ is required. Will change the example, thanks for the report.

**Comment by heistp** [comment]
Thanks for the example update, works for me now...
